FROM nginx:1.17

ARG BUILD_DATE
ARG VCS_REF
LABEL maintainer="James Hunt <images@huntprod.com>" \
      summary="Run netip.cc in a container (or two)" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/jhunt/netip.cc.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0.0"

COPY web /htdocs
COPY nginx.conf /etc/nginx/nginx.conf

# vim:ft=Dockerfile
