#!/bin/bash

NETIP_HOST=127.0.0.1
NETIP_PORT=5553
RC=0

check() {
  local name=$1
  local want=$2

  got=$(dig -p ${NETIP_PORT} +short ${name} @${NETIP_HOST})
  if [[ $got != $want ]]; then
    echo "FAIL - $name did not resolve to $want (got '$got')"
    RC=1
  else
    echo "ok $name -> $want"
  fi
}

./netip -b "${NETIP_HOST}:${NETIP_PORT}" &
NETIP_PID=$!

check 10.20.30.40.netip.cc 10.20.30.40
check a.10.20.30.40.netip.cc 10.20.30.40
check a.b.c.d.e.f.g.h.i.j.k.l.m.10.20.30.40.netip.cc 10.20.30.40
check api.system.10.244.0.34.netip.cc 10.244.0.34

for x in $(seq 0 9); do
  check ns${x}.netip.cc $NETIP_HOST
done
check ns.netip.cc ''
check ns10.netip.cc ''

check yahoo.com ''
check x.0.0.0.0.netip.cc ''
check x.255.255.255.255.netip.cc ''
check x.10.0.0.netip.cc '' # not enough octets
check x.10.0.0.799.netip.cc '' # hollywood ip

kill -TERM $NETIP_PID
wait $NETIP_PID
exit $RC
